Major updates to instruction flow
MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst pull request #129
Opened 2022-12-16 20:58 UTC by AngieRudduck

# Module: 00
## Lab/Demo: 00

Fixes # .

Changes proposed in this pull request:

-
-
-

2022-12-20 14:06 UTC, AngieRudduck reviewed
Minor updates made based on review.

2022-12-27 10:35 UTC, Mihai-Ac commented on Instructions/06-design-report-in-power-bi-desktop.md
> +    ![Slicer style](Linked_image_Files\06_slicer_style.png)
Photo is missing
![image](https://user-images.githubusercontent.com/110993710/209653932-2ec80c5b-29c7-40f9-8c36-83ff269e3c62.png)

2022-12-27 10:38 UTC, Mihai-Ac commented on Instructions/06-design-report-in-power-bi-desktop.md
> +     ![Picture 53](Linked_image_Files/07-stacked-column-chart.png)
Missing image here
![image](https://user-images.githubusercontent.com/110993710/209654295-7e2740db-2d41-45ee-a29c-9b0903a68526.png)

2022-12-27 10:41 UTC, Mihai-Ac commented on Instructions/06-design-report-in-power-bi-desktop.md
> +    ![Picture 93](Linked_image_Files/06-my-workspace-new.png)
Missing image
![image](https://user-images.githubusercontent.com/110993710/209654640-a796cb64-bb7a-45fd-834e-f2f1e071e3f9.png)

2022-12-27 11:37 UTC, Mihai-Ac commented on Instructions/07-design-report-in-power-bi-desktop-enhanced.md
> +     ![Picture 22](Linked_image_Files/07-my-workspace-new.png)
Missing picture
![image](https://user-images.githubusercontent.com/110993710/209661050-f8ad49be-7b4e-47f0-a3a7-236874b87e89.png)

2022-12-27 12:12 UTC, Mihai-Ac commented on Instructions/08-perform-data-analysis-in-power-bi-desktop.md
> +     ![Picture 22](Linked_image_Files/07-my-workspace-new.png)
Missing photo
![image](https://user-images.githubusercontent.com/110993710/209665013-39a430b3-6f08-4440-a8ac-01552311f749.png)

2022-12-27 12:38 UTC, Mihai-Ac commented on Instructions/09-create-power-bi-dashboard.md
> +     ![Picture 22](Linked_image_Files/07-my-workspace-new.png)
Missing image
![image](https://user-images.githubusercontent.com/110993710/209667821-ea3fb8eb-f675-4cf4-a212-5aea7d317043.png)

2022-12-27 13:36 UTC, Mihai-Ac requested changes
- Checked all labs.

- did not open .pbix files

- Created new commit for each lab with fixes for numbered comments/tips (left comments on each commit).

- Found 4 labs where images were missing (review comments left in the files. They are :

_Instructions/06-design-report-in-power-bi-desktop.md_ : 

**Slicer style](Linked_image_Files\06_slicer_style.png)
Picture 53](Linked_image_Files/07-stacked-column-chart.png)
Picture 93](Linked_image_Files/06-my-workspace-new.png**

For 
_07-design-report-in-power-bi-desktop-enhanced.md_
and
_08-perform-data-analysis-in-power-bi-desktop.md_
and
_09-create-power-bi-dashboard.md_

One image was missing: **Picture 22](Linked_image_Files/07-my-workspace-new.png)**

These images will need to be added, but everything else seems fine.

2022-12-30 01:16 UTC, merged